### ISSUE TITLE
Mise à jour du composant `Notification`

### ISSUE THREAD

**Issue by Bluzzi** [Virtual-Royaume/Royaume-Frontend#23]
## Exemple
https://sonner.emilkowal.ski/

## Todo
- [x] Il doit gérer deux états (`success` et `error`)
- [x] Il doit avoir une meilleur API (`notif.error(msg)`, `notif.success(msg)`)
- [ ] Le sens de suppression des notifications doit être fix

**Comment by Bluzzi** [comment]
L'effet est ultra bizarre pour l'instant :/

**Comment by Steellgold** [comment]
Étant donné que le projet est maintenant passé sur NextJS nous allons utiliser https://github.com/emilkowalski/sonner
